### ISSUE TITLE
how to using in code angular

### ISSUE THREAD

**Issue by nguyendu** [pkempenaers/angularjs-dropdown-tree#2]
I'm a newber code angularjs, I want using angularjs-dropdown-tree but not using, it return message error (I add code var angularjsdrt = require('angularjs-dropdown-tree'); into file app.js)
 ReferenceError: angular is not defined
    at Object.defineProperty.value (D:\Project\VSC_VINAPHONEPLUS_PM5\WORKING\20.Development\40.Code\10.Code\frameworkNodejs\node_modules\angularjs-dropdown-tree\component\component.js:3:536)
    at t (D:\Project\VSC_VINAPHONEPLUS_PM5\WORKING\20.Development\40.Code\10.Code\frameworkNodejs\node_modules\angularjs-dropdown-tree\component\component.js:1:177)
    at Object.<anonymous> (D:\Project\VSC_VINAPHONEPLUS_PM5\WORKING\20.Development\40.Code\10.Code\frameworkNodejs\node_modules\angularjs-dropdown-tree\component\component.js:3:125)
    at t (D:\Project\VSC_VINAPHONEPLUS_PM5\WORKING\20.Development\40.Code\10.Code\frameworkNodejs\node_modules\angularjs-dropdown-tree\component\component.js:1:177)
    at D:\Project\VSC_VINAPHONEPLUS_PM5\WORKING\20.Development\40.Code\10.Code\frameworkNodejs\node_modules\angularjs-dropdown-tree\component\component.js:3:36
    at Object.<anonymous> (D:\Project\VSC_VINAPHONEPLUS_PM5\WORKING\20.Development\40.Code\10.Code\frameworkNodejs\node_modules\angularjs-dropdown-tree\component\component.js:3:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
Please help me. Thanks

**Comment by pkempenaers** [comment]
Have you made anything in angularjs? Because it seems like you're not including angularjs in app.js
I propose you follow a tutorial about angularjs before you try to include external components.
Note that this module only works for angularjs (v1) and not for Angular (>v2). It's up to you to decide if learning angularjs is(v1) is worth your time at the moment.
